"""
SQLAlchemy ORM Models
"""

from datetime import datetime
from sqlalchemy import Column, String, Float, Integer, DateTime, JSON, Boolean, Text
from sqlalchemy.dialects.postgresql import UUID, JSONB

import uuid

from app.db.database import Base


class MetricSnapshot(Base):
    """Store metric snapshots for historical analysis"""
    __tablename__ = "metric_snapshots"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    timestamp = Column(DateTime, default=datetime.utcnow, index=True)
    pod_name = Column(String, index=True)
    namespace = Column(String, index=True)
    
    cpu_usage = Column(Float)
    memory_usage = Column(Float)
    disk_usage = Column(Float)
    network_in = Column(Float)
    network_out = Column(Float)
    
    created_at = Column(DateTime, default=datetime.utcnow)


class Anomaly(Base):
    """Store detected anomalies"""
    __tablename__ = "anomalies"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    timestamp = Column(DateTime, default=datetime.utcnow, index=True)
    
    pod_name = Column(String, index=True)
    namespace = Column(String, index=True)
    service_name = Column(String)
    
    anomaly_type = Column(String)  # cpu_spike, memory_leak, etc.
    severity = Column(String)  # low, medium, high, critical
    score = Column(Float)
    
    description = Column(Text)
    metadata = Column(JSONB)
    
    resolved = Column(Boolean, default=False)
    resolved_at = Column(DateTime, nullable=True)
    
    created_at = Column(DateTime, default=datetime.utcnow)


class ServiceDependency(Base):
    """Store service dependency relationships"""
    __tablename__ = "service_dependencies"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    
    source_service = Column(String, index=True)
    target_service = Column(String, index=True)
    
    communication_type = Column(String)  # http, grpc, database, etc.
    avg_latency_ms = Column(Float)
    error_rate = Column(Float)
    
    metadata = Column(JSONB)
    
    created_at = Column(DateTime, default=datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)


class Prediction(Base):
    """Store predictions for future issues"""
    __tablename__ = "predictions"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    
    pod_name = Column(String, index=True)
    namespace = Column(String, index=True)
    
    prediction_type = Column(String)  # pod_crash, oom, disk_full, etc.
    confidence = Column(Float)
    predicted_time_hours = Column(Float)
    
    reason = Column(Text)
    recommendation = Column(Text)
    
    created_at = Column(DateTime, default=datetime.utcnow)
    validated_at = Column(DateTime, nullable=True)
    was_correct = Column(Boolean, nullable=True)


class IncidentLog(Base):
    """Store infrastructure incidents"""
    __tablename__ = "incident_logs"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    timestamp = Column(DateTime, default=datetime.utcnow, index=True)
    
    incident_type = Column(String)
    severity = Column(String)
    
    affected_services = Column(JSONB)
    root_cause = Column(Text)
    resolution = Column(Text)
    
    metadata = Column(JSONB)
    
    created_at = Column(DateTime, default=datetime.utcnow)


class AgentInsight(Base):
    """Store insights generated by AI agents"""
    __tablename__ = "agent_insights"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    
    agent_name = Column(String, index=True)  # cpu_agent, memory_agent, etc.
    insight_type = Column(String)  # anomaly, correlation, recommendation
    
    target_pod = Column(String)
    target_service = Column(String)
    
    insight_text = Column(Text)
    confidence = Column(Float)
    
    metadata = Column(JSONB)
    
    created_at = Column(DateTime, default=datetime.utcnow)


class ChatMessage(Base):
    """Store chat conversation history"""
    __tablename__ = "chat_messages"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    session_id = Column(String, index=True)
    
    role = Column(String)  # user, assistant
    message = Column(Text)
    
    context = Column(JSONB)
    
    created_at = Column(DateTime, default=datetime.utcnow)
